wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1728570461.33311
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.13.4
      8:
      - 5
      - 9
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.03
